-- 13. 뷰
-- 테이블 복사
CREATE TABLE DEPT_COPY AS SELECT * FROM DEPT;
CREATE TABLE EMP_COPY AS SELECT * FROM EMP;
-- 뷰 정의하기
CREATE VIEW EMP_VIEW30 AS SELECT EMPNO, ENAME, DEPTNO FROM EMP_COPY WHERE DEPTNO = 30;
SELECT * FROM emp_view30;
-- 문제 1
CREATE VIEW EMP_VIEW20 AS SELECT EMPNO, ENAME, DEPTNO, MGR FROM EMP_COPY WHERE DEPTNO = 20;
SELECT * FROM emp_view20;
-- 유저의 뷰 정보 보기 (뷰는 실제 데이터를 가진게 아니라 쿼리문을 가지고 있음)
SELECT VIEW_NAME, TEXT FROM USER_VIEWS;
-- 뷰는 기본 테이블을 가져다가 쿼리문을 수행하기에 뷰의 원본에도 영향이 감
INSERT INTO EMP_VIEW30 VALUES(1111, 'AAAA', 30);
SELECT * FROM EMP_COPY;
-- 단순 뷰에서는 DML이 가능함
INSERT INTO EMP_VIEW30 VALUES(8000, '김천사', 30);
SELECT * FROM EMP_VIEW30;
-- 복합 뷰 생성
CREATE VIEW EMP_VIEW_DEPT AS SELECT * FROM EMP INNER JOIN DEPT USING(DEPTNO) ORDER BY EMPNO DESC;
SELECT * FROM EMP_VIEW_DEPT;
-- 문제 2
CREATE VIEW SAL_VIEW AS SELECT DNAME, MAX(SAL) AS "MAX_SAL", MIN(SAL) AS "MIN_SAL" FROM EMP_VIEW_DEPT 
GROUP BY DNAME, DEPTNO ORDER BY DEPTNO;
SELECT * FROM SAL_VIEW;
-- 뷰 삭제
DROP VIEW SAL_VIEW;
-- OR REPLACE (뷰 덮어쓰기)
-- FORCE (실제 테이블이 없어도 뷰 생성 가능)
-- WITH CHECK OPTION (특정 조건의 컬럼값 수정 방지)
-- READ ONLY (뷰를 통해서 기본 테이블의 어떤 컬럼도 내용 변경 불가)
-- 인라인 뷰
SELECT ROWID, ROWNUM, EMPNO, ENAME, HIREDATE FROM EMP;
SELECT ROWNUM, EMPNO, ENAME, HIREDATE FROM EMP ORDER BY HIREDATE ASC;
CREATE OR REPLACE VIEW VIEW_HIRE AS SELECT EMPNO, ENAME, HIREDATE FROM EMP ORDER BY HIREDATE ASC;
SELECT ROWNUM, EMPNO, ENAME, HIREDATE FROM VIEW_HIRE;
-- 문제 3
SELECT ROWNUM AS "RANKING", EMPNO, ENAME, SAL FROM (SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL IS NOT NULL
ORDER BY SAL DESC) WHERE ROWNUM <= 3;

-- 14. 시퀀스
-- 시퀀스 생성
CREATE SEQUENCE DEPT_DEPTNO_SEQ INCREMENT BY 10 START WITH 10;
-- CURRVAL, NEXTVAL 사용
SELECT DEPT_DEPTNO_SEQ.NEXTVAL FROM DUAL;
SELECT DEPT_DEPTNO_SEQ.CURRVAL FROM DUAL;
-- 기본키에 시퀀스 적용
CREATE SEQUENCE EMP_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 100000;
DROP TABLE EMP01;
CREATE TABLE EMP01 (EMPNO NUMBER(4) PRIMARY KEY, ENAME VARCHAR2(10), HIREDATE DATE);
INSERT INTO EMP01 VALUES (EMP_SEQ.NEXTVAL, '김씨', SYSDATE);
SELECT * FROM EMP01;
CREATE TABLE DEPT_EXAMPLE (DEPTNO NUMBER(4) PRIMARY KEY, DNAME VARCHAR2(15), LOC VARCHAR2(15));
-- 문제 1
CREATE SEQUENCE DEPT_SEQ START WITH 10 INCREMENT BY 10;
INSERT INTO dept_example VALUES (DEPT_SEQ.NEXTVAL, '경리부', '서울');
INSERT INTO dept_example VALUES (DEPT_SEQ.NEXTVAL, '인사부', '인천');
INSERT INTO dept_example VALUES (DEPT_SEQ.NEXTVAL, '영업부', '용인');
INSERT INTO dept_example VALUES (DEPT_SEQ.NEXTVAL, '전산부', '수원');
SELECT * FROM dept_example;

-- 15.인덱스
-- 사원 테이블 복사
DROP TABLE EMP01;
CREATE TABLE EMP01 AS SELECT* FROM EMP;
SELECT TABLE_NAME, INDEX_NAME, COLUMN_NAME FROM USER_IND_COLUMNS WHERE TABLE_NAME IN ('EMP', 'EMP01');
-- 데이터 복제
INSERT INTO EMP01 SELECT * FROM EMP01;
SELECT * FROM EMP01;
-- 검색용으로 사용할 행 추가
INSERT INTO EMP01 (EMPNO, ENAME) VALUES (1111, '홍길동');
-- 홍길동 검색
SELECT DISTINCT EMPNO, ENAME FROM EMP01 WHERE ENAME = '홍길동';
-- 인덱스 생성
CREATE INDEX IDX_EMP_ENAME ON EMP01(ENAME);
-- 인덱스 생성 후 홍길동 검색
SELECT DISTINCT EMPNO, ENAME FROM EMP01 WHERE ENAME = '홍길동';

-- 자바와 연동
CREATE TABLE person (name VARCHAR2(20), age NUMBER, region VARCHAR2(50));
SELECT * FROM person;