-- 08.서브 쿼리
-- 문제 1
SELECT * FROM emp WHERE job = (SELECT job FROM emp WHERE ename = '김사랑');
-- 문제 2
SELECT ename, sal FROM emp WHERE sal >= (SELECT sal FROM emp WHERE ename = '김사랑');
-- 문제 3
SELECT ename, sal FROM emp WHERE deptno = (SELECT deptno FROM dept WHERE loc = '용인');
-- 문제 4
SELECT ename, sal FROM emp WHERE mgr = (SELECT empno FROM emp WHERE ename = '장동건');
-- 문제 5
SELECT * FROM emp WHERE sal IN (SELECT DISTINCT MAX(sal) FROM emp GROUP BY deptno);
-- 문제 6
SELECT * FROM dept WHERE deptno IN (SELECT DISTINCT deptno FROM emp WHERE job = '과장') ORDER BY deptno ASC;
-- 문제 7
SELECT ename, sal, job FROM emp WHERE sal > all (SELECT DISTINCT sal FROM emp WHERE job = '과장');
-- 문제 8
SELECT ename, sal, job FROM emp WHERE sal > any (SELECT DISTINCT sal FROM emp WHERE job = '과장');

-- 09.DDL
-- 문제 1
CREATE TABLE EMP01 (EMPNO NUMBER(4), ENAME VARCHAR2(20), HEIGHT NUMBER(5,2), ADDRESS VARCHAR2(200), PHONE VARCHAR2(20));
-- 문제 2
CREATE TABLE EMP02 AS SELECT * FROM EMP;
SELECT * FROM EMP02;
-- 문제 3
CREATE TABLE EMP03 AS SELECT EMPNO, ENAME FROM EMP;
SELECT * FROM EMP03;
-- 문제 4
CREATE TABLE EMP04 AS SELECT * FROM EMP WHERE DEPTNO = 10;
SELECT * FROM EMP04;
CREATE TABLE EMP06 AS SELECT EMPNO, ENAME, SAL FROM EMP;
SELECT * FROM EMP06;
ALTER TABLE EMP01 ADD (JOB VARCHAR2(9));
DESC EMP01;
ALTER TABLE EMP01 DROP COLUMN JOB;
DROP TABLE DEPT01;
CREATE TABLE DEPT01 AS SELECT * FROM DEPT WHERE 1=0;
INSERT INTO DEPT01 (DEPTNO, DNAME, LOC) VALUES (10, '영업부', '부산');

-- 10.DML
-- 문제 1
CREATE TABLE SAM01 (EMPNO NUMBER(4), ENAME VARCHAR2(10), JOB VARCHAR2(9), SAL NUMBER(7, 2));
INSERT INTO SAM01 (EMPNO, ENAME, JOB, SAL) VALUES(1000, '사과', '경찰', 1000);
INSERT INTO SAM01 (EMPNO, ENAME, JOB, SAL) VALUES(1010, '바나나', '간호사', 1500);
INSERT INTO SAM01 (EMPNO, ENAME, JOB, SAL) VALUES(1020, '오렌지', '의사', 2000);
SELECT * FROM SAM01;
COMMIT;

-- 문제 2
INSERT INTO SAM01 (EMPNO, ENAME, SAL) VALUES(1030, '베리', 2500);
INSERT INTO SAM01 VALUES(1040, '망고', NULL, 25000);
SELECT * FROM SAM01;
COMMIT;

DROP TABLE DEPT02;
CREATE TABLE DEPT02 AS SELECT * FROM DEPT WHERE 1=0;
INSERT INTO DEPT02 SELECT * FROM DEPT;
SELECT * FROM DEPT02;
COMMIT;

-- 문제 3
INSERT INTO SAM01 SELECT EMPNO, ENAME, JOB, SAL FROM EMP WHERE DEPTNO = '10';
SELECT * FROM SAM01;
COMMIT;

DROP TABLE EMP01;
CREATE TABLE EMP01 AS SELECT * FROM EMP;
SELECT * FROM EMP01;
COMMIT;

-- 문제 4
UPDATE EMP01 SET DEPTNO = 30 WHERE DEPTNO = 10;
SELECT * FROM EMP01;
COMMIT;

-- 문제 5
UPDATE EMP01 SET SAL = SAL * 1.1 WHERE SAL >= 400;
SELECT * FROM EMP01;
COMMIT;

-- 문제 6
UPDATE SAM01 SET SAL = SAL - 5000 WHERE SAL >= 10000;
SELECT * FROM SAM01;
COMMIT;

-- 문제 7
CREATE TABLE SAM02 (ENAME VARCHAR2(10), SAL NUMBER(7,2), HIREDATE DATE, DEPTNO NUMBER(2));
INSERT INTO SAM02 SELECT ENAME, SAL, HIREDATE, DEPTNO FROM EMP;
SELECT * FROM SAM02;
COMMIT;

-- 문제 8
UPDATE SAM02 SET SAL = (SAL + 100) WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC = '인천');
SELECT * FROM SAM02;
COMMIT;

-- 문제 9
DELETE FROM SAM01 WHERE job IS NULL;
SELECT * FROM SAM01;
COMMIT;

-- 문제 10
DELETE FROM SAM02 WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = '영업부');
SELECT * FROM SAM02;
COMMIT;

SELECT * FROM DEPT01;
COMMIT;
DELETE FROM DEPT01 WHERE DEPTNO = 40;
COMMIT;
DELETE FROM DEPT01 WHERE DEPTNO = 30;
SAVEPOINT C1;
DELETE FROM DEPT01 WHERE DEPTNO = 20;
SAVEPOINT C2;
DELETE FROM DEPT01 WHERE DEPTNO = 10;
ROLLBACK TO C1;
ROLLBACK TO C2;
ROLLBACK;
DESC
EMP;